// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knpsozbkxaugqeaoffwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtucHNvemJreGF1Z3FlYW9mZndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDcwODIsImV4cCI6MjA2NDA4MzA4Mn0.Emex76122tHE3dwTLsoT1ebTpUovUE99FfX_F8i3MOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);